data_paths: ['data/simsat5625.dill', 'data/imerg_5625.dill', 'data/era5625_aaai.dill']
norm_path: 'PyRain\analysis\precip_estimation\normalise\5625__16-04-01_12_00to17-12-31_11_00.json' # Should be an absolute path, NOTE: these files need to manually be added
log_path: '/data/forecast_benchmark/'